### ISSUE TITLE
Fix YouTube URLs

### ISSUE THREAD

**Issue by elibroftw** [Mitrichius/hugo-theme-anubis#120]
Anubis links to `/c/username` instead of `/channel/username`

[https://www.youtube.com/channel/UCIrKT6IOvPo_oT4zSUm6uhQ](https://www.youtube.com/channel/UCIrKT6IOvPo_oT4zSUm6uhQ)
vs.
[https://www.youtube.com/c/UCIrKT6IOvPo_oT4zSUm6uhQ](https://www.youtube.com/c/UCIrKT6IOvPo_oT4zSUm6uhQ)

Additionally, it would be better if you would allow social URL overrides for built in social support.

**Comment by Mitrichius** [comment]
`/c/username` is a valid youtube channel link for custom URLs (check https://support.google.com/youtube/answer/6180214?hl=en).
I added custom urls for predefined icons, so you could use this:
```
  - id: youtube
    url: "https://www.youtube.com/channel/UCIrKT6IOvPo_oT4zSUm6uhQ"
```

P.S. I understand that your link is valid too, but due to backward compatibility, I left `/c/username` as default one.

**Comment by elibroftw** [comment]
Good enough thanks.
