### ISSUE TITLE
Incorrect Rendering of Mardown Features that Require Tags

### ISSUE THREAD

**Issue by bpiv400** [Mitrichius/hugo-theme-anubis#40]
Hi,

First, great theme! Thanks for making this. 

Now, I noticed that in the demo site, the other elements section of the [Markdown Syntax Introduction article ](https://themes.gohugo.io//theme/hugo-theme-anubis/post/markdown-syntax/)doesn't render properly. In my browser, the text just renders as plain content text. I observe the same problem in my personal website running Anubis. I know this isn't purely a browser issue because the elements do render with the correct formatting when I use or demo other themes. Do you have the same problem?  

I'm very new to Hugo, so I have no idea what might cause this. But I'll try to look into it and let you know if I find anything.

**Comment by Mitrichius** [comment]
Hi!

Thank you for pointing to this.
It happens because Hugo new versions changed markdown engine and html rendering are disabled by default now. 
I enabled it for demo site and updated config example in README file.

If it's ok now, please, close issue :)

P.S. Please note that it take some time for demo site to update

**Comment by bpiv400** [comment]
Got it! Thanks!
