### ISSUE TITLE
Failing to build website on Gitlab

### ISSUE THREAD

**Issue by julian-englert** [Mitrichius/hugo-theme-anubis#70]
Hi, I'm using your theme for my website https://jenglert.gitlab.io :) In the past couple of days I haven't been able to get Gitlab to successfully build the site. 

(my last build was two weeks and I encountered the error first when I tried to publish something ~4 days ago)

"ERROR 2020/11/05 22:24:15 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request"

from the most recent failed build: https://gitlab.com/jenglert/jenglert.gitlab.io/-/jobs/833399295

On my local machine I got the error too when running `hugo server` but I got rid of it using _ignoreErrors_ in my config.toml as described [here on the Hugo forum](https://discourse.gohugo.io/t/how-to-handle-getjson-errors/8351/6)

I saw that the theme was updated on October 29 - do I have to change something with my website in order to build it properly with the updated version? :)

**Comment by Mitrichius** [comment]
Hi, I fixed this. 
The problem was in the example site: shortcode for Instagram responds with HTTP error.  
I checked the official example site and this shortcode was deleted from it (check [this commit](https://github.com/gohugoio/hugoBasicExample/commit/25c5b2f54c5162007c1afc467bf33015f250ff0f)). So I did the same. 

You should create a new site from example one or just remove Instagram shortcode.

**Comment by julian-englert** [comment]
Thanks a lot for the fast help, it was indeed the Instagram shortcode in the `rich-content.md` example that was still sitting in my `/content/posts/` directory. Removed it and now it builds again :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
